DROP TABLE IF EXISTS search;

CREATE TABLE search (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    search_text TEXT NOT NULL,
    result_count INTEGER NOT NULL,
    result_type TEXT NOT NULL,
    lang TEXT NOT NULL
);